MODEL:
  TYPE: regnet
  NUM_CLASSES: 100
  LOSS_FUN: cross_entropy
REGNET:
  STEM_TYPE: res_stem_cifar # Stem type: [res_stem_cifar,res_stem_in, simple_stem_in]
  STEM_W: 32 # Stem width
  BLOCK_TYPE: res_bottleneck_block # Block type: [res_basic_block,res_bottleneck_block,res_bottleneck_linear_block]
  STRIDE: 2 # Stride of each stage
  SE_ON: True # Squeeze-and-Excitation (RegNetY)
  SE_R: 0.25

  DEPTH: 20 # Depth
  W0: 232 # Initial width
  WA: 115.89 #Slope
  WM: 2.53 # Quantization

  GROUP_W: 8 # Group width
  BOT_MUL: 1.0 # Bottleneck multiplier (bm = 1 / b from the paper)
  
OPTIM:
  LR_POLICY: cos
  BASE_LR: 0.2
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  WEIGHT_DECAY: 5e-5
  WARMUP_EPOCHS: 5
TRAIN:
  DATASET: cifar100
  IM_SIZE: 32
  BATCH_SIZE: 256
TEST:
  DATASET: cifar100
  IM_SIZE: 32
  BATCH_SIZE: 200
NUM_GPUS: 8
OUT_DIR: .