EXPERIMENT:
  NAME: ""
  PROJECT: ""
DISTILLER:
  TYPE: "NONE"
  TEACHER: "NONE"
  STUDENT: "None"
SOLVER:
  BATCH_SIZE: 128
  EPOCHS: 100
  LR: 0.001
  MIN_LR: 0.0000
  LR_SCHEDULER: "cosine_annealing"
  SCHEDULER_EPOCHS: 100
  WARMUP: True
  LABEL_SMOOTHING: 0.1
  WEIGHT_DECAY: 0.01
  MOMENTUM: 0.9
  TYPE: "Adam"
  SWA_START: 90
  TOPK: 2