EXPERIMENT:
  NAME: ""
  PROJECT: "DKD_tests"
  LOGIT_STAND: True
DISTILLER:
  TYPE: "DKD"
  TEACHER: "resnet18"
  STUDENT: "ind1"
DKD:
  ALPHA: 1.0
  BETA: 2.0
  CE_WEIGHT: 1.0
  T: 4.0
  WARMUP: 1
SOLVER:
  BATCH_SIZE: 128
  EPOCHS: 10
  LR: 0.001
  MIN_LR: 0.0
  LR_SCHEDULER: "cosine_annealing"
  SCHEDULER_EPOCHS: 50
  WARMUP: True
  LABEL_SMOOTHING: 0.25
  WEIGHT_DECAY: 0.01
  MOMENTUM: 0.9
  TYPE: "Adam"
  TOPK: 2
