EXPERIMENT:
  NAME: ""
  PROJECT: "KD_tests"
  LOGIT_STAND: True
DISTILLER:
  TYPE: "NONE"
  TEACHER: "resnet18"
  STUDENT: "ind1"
KD:
  TEMPERATURE: 3
  LOSS:
    CE_WEIGHT: 0.1
    KD_WEIGHT: 18
    KD_EPOCHS: 10
    KD_REDUCTION: 1
SOLVER:
  BATCH_SIZE: 128
  EPOCHS: 10
  LR: 0.001
  MIN_LR: 0.0
  LR_SCHEDULER: "cosine_annealing"
  SCHEDULER_EPOCHS: 50
  WARMUP: False
  LABEL_SMOOTHING: 0.1
  WEIGHT_DECAY: 0.01
  MOMENTUM: 0.9
  TYPE: "Adam"
  TOPK: 2
