MODEL:
  TYPE: regnet
  NUM_CLASSES: 0
REGNET:
  STEM_TYPE: res_stem_cifar # Stem type: [res_stem_cifar,res_stem_in, simple_stem_in]
  STEM_W: 32 # Stem width
  BLOCK_TYPE: res_bottleneck_block # Block type: [res_basic_block,res_bottleneck_block,res_bottleneck_linear_block]
  STRIDE: 2 # Stride of each stage
  SE_ON: True # Squeeze-and-Excitation (RegNetY)
  SE_R: 0.25
  DOWNSAMPLE: avg #AVG as resnet-D, conv1x1 as resnet. 
  DROP_RATE: 0.01 #Stochastic drop path rate
  DROPOUT: 0.2

  DEPTH: 20 # Depth
  W0: 232 # Initial width
  WA: 115.89 #Slope
  WM: 2.53 # Quantization
  GROUP_W: 8 # Group width

  BOT_MUL: 1.0 # Bottleneck multiplier (bm = 1 / b from the paper)
  