EXPERIMENT:
  NAME: ""
  PROJECT: ""
DISTILLER:
  TYPE: "NONE"
  TEACHER: "NONE"
  STUDENT: "None"
SOLVER:
  BATCH_SIZE: 128
  EPOCHS: 10
  LR: 1e-4
  MIN_LR: 0.25e-4
  LR_SCHEDULER: "cosine_annealing" # Step # one_cycle
  WARMUP: False # Half epoch warmup 
  LABEL_SMOOTHING: 0.1
  WEIGHT_DECAY: 1e-2
  MOMENTUM: 0.9
  SWA_START: 3
  TYPE: "Lion" # SGD # AdamW
  TOPK: 2