EXPERIMENT:
  NAME: ""
  PROJECT: ""
DISTILLER:
  TYPE: "NONE"
  TEACHER: "NONE"
  STUDENT: "None"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 2
  LR: 0.01
  LR_SCHEDULER: "cosine_annealing"
  WARMUP: True
  LABEL_SMOOTHING: 0.0
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
  TOPK: 5