EXPERIMENT:
  NAME: ""
  PROJECT: ""
DISTILLER:
  TYPE: "NONE"
  TEACHER: "NONE"
  STUDENT: "None"
SOLVER:
  BATCH_SIZE: 128
  EPOCHS: 20
  LR: 0.01
  LR_SCHEDULER: "cosine_annealing"
  SCHEDULER_EPOCHS: 20
  MIN_LR: 0.0000
  #LR_SCHEDULER: "one_cycle"
  WARMUP: True
  LABEL_SMOOTHING: 0.1
  WEIGHT_DECAY: 0.00004
  MOMENTUM: 0.9
  TYPE: "SGD"
  SWA_START: 12
  TOPK: 2