EXPERIMENT:
  NAME: ""
  PROJECT: ""
DISTILLER:
  TYPE: "NONE"
  TEACHER: "NONE"
  STUDENT: "None"
SOLVER:
  BATCH_SIZE: 128
  EPOCHS: 50
  LR: 0.025
  LR_SCHEDULER: "cosine_annealing"
  MIN_LR: 0.0
  #LR_SCHEDULER: "one_cycle"
  WARMUP: True
  LABEL_SMOOTHING: 0.1
  WEIGHT_DECAY: 0.00004
  MOMENTUM: 0.9
  TYPE: "SGD"
  SWA_START: 40
  TOPK: 2