EXPERIMENT:
  NAME: ""
  PROJECT: ""
DISTILLER:
  TYPE: "NONE"
  TEACHER: "NONE"
  STUDENT: "None"
SOLVER:
  BATCH_SIZE: 128
  EPOCHS: 20
  LR: 0.001
  MIN_LR: 0.0
  LR_SCHEDULER: "cosine_annealing"
  SCHEDULER_EPOCHS: 40
  WARMUP: True
  LABEL_SMOOTHING: 0.1
  WEIGHT_DECAY: 0.01
  MOMENTUM: 0.9
  TYPE: "Adam"
  TOPK: 2