EXPERIMENT:
  NAME: ""
  TAG: "kd,parent,ind1,2,9"
  PROJECT: "test_regnet_cifar100/Generation_1_kinh"
DISTILLER:
  TYPE: "ParentsKD"
  TEACHER: "ind1"
  STUDENT: "ind1"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 5
  LR: 0.025
  LR_DECAY_STAGES: [1,2,3,4]
  LR_DECAY_RATE: 0.75
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"

