EXPERIMENT:
  NAME: ""
  PROJECT: ""
DISTILLER:
  TYPE: "NONE"
  TEACHER: "NONE"
  STUDENT: "None"
SOLVER:
  BATCH_SIZE: 128
  EPOCHS: 5
  LR: 0.01
  MIN_LR: 0.0025
  LR_SCHEDULER: "cosine_annealing"
  SCHEDULER_EPOCHS: 5
  WARMUP: False
  LABEL_SMOOTHING: 0.1
  WEIGHT_DECAY: 0.00004
  MOMENTUM: 0.9
  TYPE: "SGD"
  TOPK: 2